a=input("Digite algo:")
print("O tipo primitivo desse valor é:",type(a))
print("É um número:", a.isnumeric())
print("Só tem espaços:",a.isspace())
print("Só tem letras:",a.isalpha())
print("É alfanúmerico:",a.isalnum())
print("Está em maiúsculo:",a.isupper())
print("Está em minúsculo:",a.islower())
print("Está capitalizada",a.istitle())
print("É {} que esse texto está capitalizado".format(a.istitle()))
