num=int(input("O número da tabuada é:"))
num1= num*1
num2= num*2
num3= num*3
num4= num*4
num5= num*5
num6= num*6
num7= num*7
num8= num*8
num9= num*9
num10= num*10
print("{} x {} = {}".format(num, 1, num1))
print("{} x {} = {}".format(num, 2, num2))
print("{} x {} = {}".format(num, 3, num3))
print("{} x {} = {}".format(num, 4, num4))
print("{} x {} = {}".format(num, 5, num5))
print("{} x {} = {}".format(num, 6, num6))
print("{} x {} = {}".format(num, 7, num7))
print("{} x {} = {}".format(num, 8, num8))
print("{} x {} = {}".format(num, 9, num9))
print("{} x {} = {}".format(num, 10, num10))